# Generated by Django 6.0.3 on 2026-03-16 17:17

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='bank',
            field=models.CharField(
                choices=[
                    ('BANCO_NORTE', 'Banco Norte'),
                    ('CREDIFUTURO', 'CrediFuturo'),
                    ('BANCO_CAPITAL', 'Banco Capital'),
                    ('FINANZAS_DEL_SUR', 'Finanzas del Sur'),
                    ('EUROBANK_LOCAL', 'Eurobank Local'),
                ],
                default='BANCO_NORTE',
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='account_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='reviewed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reviewed_claims',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]