# Generated by Django 6.0.3 on 2026-03-14 16:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('FISH', 'Fish'), ('RABBIT', 'Rabbit'), ('HAMSTER', 'Hamster'), ('GUINEA_PIG', 'Guinea Pig'), ('TURTLE', 'Turtle'), ('FERRET', 'Ferret'), ('SNAKE', 'Snake'), ('LIZARD', 'Lizard'), ('OTHER', 'Other')], max_length=10)),
                ('birth_date', models.DateField()),
                ('coverage_start', models.DateField(default=django.utils.timezone.now)),
                ('coverage_end', models.DateField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
